name: publish to npm

on:
  release:
    types: [created] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci 
      - run: |
          VERSION=${GITHUB_REF#refs/tags/}
          npm version $VERSION --no-git-tag-version
      - run: |          
          git config user.name "priscila-martins-sh3"
          git config user.email "priscila.martins@sh3.com.br"
          git add package.json package-lock.json
          git commit -m "chore(version): version bump ${GITHUB_REF#refs/tags/}"
          git push
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
