name: publish to npm

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
            ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm ci       
      - run: npm run build
      - run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
